hr:
    resource: "@HrBundle/Resources/config/routing.yml"
    prefix:   /

attendance_reg:
    resource: "@AttendanceRegBundle/Resources/config/routing.yml"
    prefix:   /attendance

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
