employee_index:
    path:     /
    defaults: { _controller: "AttendanceRegBundle:Employee:index" }
    methods:  GET

employee_show:
    path:     /{id}/show
    defaults: { _controller: "AttendanceRegBundle:Employee:show" }
    methods:  GET

employee_new:
    path:     /new
    defaults: { _controller: "AttendanceRegBundle:Employee:new" }
    methods:  [GET, POST]

employee_edit:
    path:     /{id}/edit
    defaults: { _controller: "AttendanceRegBundle:Employee:edit" }
    methods:  [GET, POST]

employee_delete:
    path:     /{id}/delete
    defaults: { _controller: "AttendanceRegBundle:Employee:delete" }
    methods:  DELETE
